services:
  - type: web
    name: engine-inspection
    runtime: python
    buildCommand: "./render-build.sh"
    startCommand: "python main.py"
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
